version: "3.9"

services:
  db_calc:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  calc:
    build: .
    command: >
      sh -c "
        cd shape_calculate &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/shape_calculate
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db_calc
